/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Auth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "Bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "GoogleClientID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Hono": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "HostedZone": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Stripe": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "StripeAPIKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeEndpointSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Web": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}