/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_API_URL: string
  readonly VITE_AUTH_URL: string
  readonly VITE_STRIPE_BASIC_PAYMENT_LINK: string
  readonly VITE_STRIPE_PRO_PAYMENT_LINK: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}